docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
site_name: 'laminas-zendframework-bridge'
site_description: 'Alias legacy ZF class names to Laminas Project equivalents.'
repo_url: 'https://github.com/laminas/laminas-zendframework-bridge'
